#!/usr/bin/env python3
"""StoryWeaver book ingest for the lily-game library shelf (stdlib only).

Pratham Books / StoryWeaver content is CC BY 4.0. This CLI gathers a curation
shortlist so the PM can pick 18 titles for the in-game library shelf.

Subcommands
-----------
candidates
    Page through the StoryWeaver ``books-search`` JSON API (no auth), filter
    client-side for English level 1-3 non-GIF storybooks of a usable length,
    and write a shortlist to:

    * /tmp/kilo/book-candidates.json  -- machine list (~40 candidates)
    * /tmp/kilo/book-candidates.md    -- human table + excluded notable titles

download
    Fetch a curated shelf of books into ``library/books/{id}/`` (stdlib only):

    * ``thumb.jpg``            -- storycard cover thumb (metadata size1 url)
    * ``page-01.jpg`` ...      -- size7 page images in book order
    * ``book.json``            -- metadata + per-page text + CC BY attribution
    * ``library/books/index.json`` -- raw ordered shelf index

    Ingest chain (live-verified): ``/api/v1/stories/{id}`` metadata (title is
    under ``name``; ``lastPagePosition`` = page count) -> cover page id from
    ``/stories/show-in-iframe/{id}`` -> ONE XHR GET of
    ``/en/v0/stories/{slug}/pages/{pageId}`` returning the whole book as a
    JS-string-escaped HTML payload (unescape ``\\"`` first, then ``\\'``, then
    ``\\/``, ONLY THEN run HTML regexes). Page blocks carry
    ``responsive_illustration`` images (download ``data-size7-src``) and
    ``content``/``newStories`` textboxes; unimaged credits/back-cover blocks
    supply the verbatim attribution text (CC BY 4.0). Resume-tolerant: a book
    with a valid ``book.json`` and all valid JPEGs is skipped on re-runs.

manifest
    Regenerate the catalog/attribution artifacts from the ``book.json`` files
    already on disk (no network, deterministic -- no timestamps in output):

    * ``library/manifest.json``       -- the game's shelf catalog (all paths
      relative to ``library/``, books sorted by ``shelfOrder`` from book.json)
    * ``library/CREDITS.md``          -- the CC BY attribution sheet: one entry
      per book (standard CC BY pattern + the verbatim ``attribution`` text)
    * ``THIRD-PARTY-NOTICES.md``      -- the StoryWeaver section is appended at
      the end; re-runs replace that section in place (idempotent, never
      duplicated)

reimage
    Data-fix pass over an already-downloaded shelf: every ``page-*.jpg`` larger
    than 300KB (300 * 1024 B) is replaced by the next smaller CDN variant of
    the SAME illustration crop -- ``.../illustration_crops/{crop}/size7/{hash}.jpg``
    -> ``size6`` -> ``size5`` -- chosen per page: start at size7; if the result
    would exceed 300KB drop to size6; if still over 300KB drop to size5; if
    STILL over 300KB keep size5 and warn. Files at/under the cap are never
    touched (old-era ~117KB size7 pages stay byte-identical), ``thumb.jpg``
    stays size1, and ``book.json`` is not modified (it stores no byte sizes).
    Page source URLs are re-derived from the cached pages payload per book
    (one small XHR per book, cache-warm = zero network).

audio
    Stamp/unstamp the page-narration audio fields (clips generated by
    ``tools/fetch_audio.py``): scan ``library/books/*/audio/page-NN.{mp3,wav}``
    and set each book.json ``pages[].audio`` to the book-relative path (e.g.
    ``audio/page-02.mp3``); stale ``audio`` fields whose files are gone are
    removed and nothing else in book.json is touched. Then regenerate
    manifest + CREDITS through the SAME code path ``manifest`` uses (no forked
    writers). A book carrying any ``audio`` gains one CREDITS.md line
    crediting Xiaomi MiMo TTS (idempotent upsert).

Network policy
--------------
Sequential GETs only, polite User-Agent, 20 s timeout, one retry, and every
response is cached under /tmp/kilo/fetch-books-cache/ so an interrupted run
resumes without re-fetching (pass ``--no-cache`` to force fresh reads).
"""

from __future__ import annotations

import argparse
import hashlib
import html
import json
import re
import sys
import textwrap
import time
import urllib.error
import urllib.parse
import urllib.request
from pathlib import Path

USER_AGENT = "lily-game-book-ingest/1.0 (educational use; contact via lily.game)"
TIMEOUT_S = 20
API_BASE = "https://storyweaver.org.in/api/v1"
SITE_BASE = "https://storyweaver.org.in"

OUT_DIR = Path("/tmp/kilo")
CACHE_DIR = OUT_DIR / "fetch-books-cache"
JSON_OUT = OUT_DIR / "book-candidates.json"
MD_OUT = OUT_DIR / "book-candidates.md"

# --- curation knobs -------------------------------------------------------
TARGET_ENGLISH = 150   # stop paging once this many English books are collected
                       # (spec floor is 120; 150 gives the filters some slack)
META_FETCH_LIMIT = 60  # per-story metadata fetches (top by reads) for page counts
META_FETCH_HARD_CAP = 80
META_FETCH_BATCH = 10
FINAL_TARGET = 40      # shortlist size we aim for after the page-count filter
MIN_PAGES = 6
MAX_PAGES = 20
MAX_SEARCH_PAGES = 20  # safety valve on books-search paging
NOTABLE_LIMIT = 25     # rows in "Excluded notable titles"

ALLOWED_LEVELS = {"1", "2", "3"}


# ---------------------------------------------------------------------------
# HTTP layer (shared by this subcommand and the future `download` one)
# ---------------------------------------------------------------------------

class Fetcher:
    """Sequential urllib GETs: polite UA, 20 s timeout, one retry, disk cache."""

    def __init__(self, use_cache: bool = True) -> None:
        self.use_cache = use_cache
        self.total_bytes = 0
        self.requests = 0
        self.cache_hits = 0
        OUT_DIR.mkdir(parents=True, exist_ok=True)
        if use_cache:
            CACHE_DIR.mkdir(parents=True, exist_ok=True)

    def _cache_path(self, url: str) -> Path:
        digest = hashlib.sha256(url.encode("utf-8")).hexdigest()[:24]
        return CACHE_DIR / f"{digest}.json"

    def get_text(self, url: str, headers: dict | None = None) -> str:
        """GET ``url`` and return the body as text (cached across runs)."""
        cpath = self._cache_path(url)
        if self.use_cache and cpath.exists():
            try:
                self.cache_hits += 1
                return json.loads(cpath.read_text(encoding="utf-8"))["body"]
            except (OSError, ValueError, KeyError):
                pass  # corrupt cache entry -> refetch

        last_err: Exception | None = None
        for attempt in (1, 2):
            try:
                req_headers = {"User-Agent": USER_AGENT}
                if headers:
                    req_headers.update(headers)
                req = urllib.request.Request(url, headers=req_headers)
                with urllib.request.urlopen(req, timeout=TIMEOUT_S) as resp:
                    body = resp.read()
                self.requests += 1
                self.total_bytes += len(body)
                text = body.decode("utf-8", errors="replace")
                if self.use_cache:
                    cpath.write_text(
                        json.dumps({"url": url, "body": text}), encoding="utf-8"
                    )
                return text
            except Exception as err:  # URLError / HTTPError / TimeoutError / ...
                last_err = err
                print(f"  ! fetch attempt {attempt} failed: {url}: {err}", file=sys.stderr)
                if attempt == 1:
                    time.sleep(1.0)
        raise RuntimeError(f"fetch failed after retry: {url}: {last_err}")

    def get_json(self, url: str, headers: dict | None = None) -> dict:
        return json.loads(self.get_text(url, headers=headers))

    def _cache_path_bin(self, url: str) -> Path:
        digest = hashlib.sha256(url.encode("utf-8")).hexdigest()[:24]
        return CACHE_DIR / f"{digest}.bin"

    def get_bytes(self, url: str, headers: dict | None = None) -> bytes:
        """GET ``url`` and return raw bytes (cached across runs, like get_text)."""
        cpath = self._cache_path_bin(url)
        if self.use_cache and cpath.exists():
            try:
                body = cpath.read_bytes()
            except OSError:
                body = b""
            if body:
                self.cache_hits += 1
                return body

        last_err: Exception | None = None
        for attempt in (1, 2):
            try:
                req_headers = {"User-Agent": USER_AGENT}
                if headers:
                    req_headers.update(headers)
                req = urllib.request.Request(url, headers=req_headers)
                with urllib.request.urlopen(req, timeout=TIMEOUT_S) as resp:
                    body = resp.read()
                self.requests += 1
                self.total_bytes += len(body)
                if self.use_cache:
                    cpath.write_bytes(body)
                return body
            except Exception as err:  # URLError / HTTPError / TimeoutError / ...
                last_err = err
                print(f"  ! fetch attempt {attempt} failed: {url}: {err}", file=sys.stderr)
                if attempt == 1:
                    time.sleep(1.0)
        raise RuntimeError(f"fetch failed after retry: {url}: {last_err}")

    def stats(self) -> str:
        mb = self.total_bytes / (1024.0 * 1024.0)
        return (
            f"{self.requests} requests, {self.total_bytes:,} bytes ({mb:.2f} MiB), "
            f"{self.cache_hits} cache hits"
        )


# ---------------------------------------------------------------------------
# helpers
# ---------------------------------------------------------------------------

def search_url(page: int, per_page: int, levels: list[str] | None = None) -> str:
    """Build a books-search URL. Keys keep the ``[]`` suffix the API expects."""
    params: list[tuple[str, str]] = [
        ("languages[]", "English"),
        ("sort", "Most Read"),
        ("page", str(page)),
        ("per_page", str(per_page)),
    ]
    for lv in levels or []:
        params.append(("levels[]", str(lv)))
    return f"{API_BASE}/books-search?{urllib.parse.urlencode(params)}"


def story_url(book_id) -> str:
    return f"{API_BASE}/stories/{book_id}"


def reads_of(book: dict) -> int:
    try:
        return int(book.get("readsCount") or 0)
    except (TypeError, ValueError):
        return 0


def likes_of(book: dict) -> int:
    try:
        return int(book.get("likesCount") or 0)
    except (TypeError, ValueError):
        return 0


def level_of(book: dict) -> str:
    return str(book.get("level") or "").strip()


def is_gif(book: dict) -> bool:
    return book.get("isGif") in (True, 1, "1", "true", "True")


def name_list(value) -> list[str]:
    """Normalize authors[]/illustrators[] entries to a list of strings."""
    out: list[str] = []
    for item in value or []:
        if isinstance(item, str):
            out.append(item.strip())
        elif isinstance(item, dict):
            out.append(str(item.get("name") or item.get("title") or "").strip())
        else:
            out.append(str(item).strip())
    return [n for n in out if n]


def cover_thumb_url(book: dict) -> str | None:
    """Smallest available cover size (thumb is fine for the curation sheet)."""
    sizes = ((book.get("coverImage") or {}).get("sizes")) or []
    scored: list[tuple[int, str]] = []
    for size in sizes:
        url = size.get("url")
        if not url:
            continue
        try:
            width = int(size.get("width") or 0)
        except (TypeError, ValueError):
            width = 0
        scored.append((width if width > 0 else 10**9, url))
    if not scored:
        return None
    scored.sort(key=lambda pair: pair[0])
    return scored[0][1]


def one_line(text: str | None, limit: int = 90) -> str:
    """Whitespace-collapse, entity-unescape, truncate to ~90 chars for the MD."""
    flat = html.unescape(re.sub(r"\s+", " ", text or "")).strip()
    if len(flat) <= limit:
        return flat
    cut = flat[: limit - 1].rsplit(" ", 1)[0] or flat[: limit - 1]
    return cut + "..."


def md_cell(text: str | None) -> str:
    """Make a string safe for a markdown table cell."""
    return (text or "").replace("|", "\\|").replace("\n", " ").strip()


# Lightweight keyword themes derived from the description/title only.
# Editorial content stays limited to this column (per curation rules).
THEME_KEYWORDS: tuple[tuple[str, tuple[str, ...]], ...] = (
    ("bedtime", ("bed", "bedtime", "sleep", "sleepy", "night", "moon", "star",
                 "stars", "dream", "dreams", "dark", "nap", "yawn", "midnight")),
    ("animals", ("cat", "cats", "dog", "dogs", "monkey", "monkeys", "tiger",
                 "tigers", "elephant", "elephants", "bird", "birds", "fish",
                 "frog", "frogs", "bear", "bears", "rabbit", "rabbits", "deer",
                 "snake", "snakes", "ant", "ants", "bee", "bees", "cow", "cows",
                 "goat", "goats", "hen", "hens", "crow", "crows", "parrot",
                 "parrots", "squirrel", "squirrels", "mouse", "mice", "lion",
                 "lions", "fox", "foxes", "wolf", "wolves", "duck", "ducks",
                 "snail", "snails", "crab", "crabs", "whale", "whales",
                 "donkey", "kitten", "puppy", "puppies", "horse", "horses",
                 "sheep", "owl", "owls", "pigeon", "sparrow", "butterfly",
                 "caterpillar", "tortoise", "turtle")),
    ("family", ("mother", "father", "amma", "appa", "grandma", "grandmother",
                "grandfather", "grandpa", "sister", "brother", "baby", "family",
                "parents", "mama", "papa", "aunt", "uncle", "sibling")),
    ("friendship", ("friend", "friends", "friendship", "share", "shares",
                    "sharing", "together", "play", "plays", "playing")),
    ("school", ("school", "teacher", "teachers", "learn", "learns", "learning",
                "class", "classroom", "student", "students", "lesson", "book",
                "books", "read", "reading", "write", "homework")),
    ("nature", ("tree", "trees", "forest", "forests", "river", "rivers", "rain",
                "rains", "sun", "flower", "flowers", "garden", "mountain",
                "mountains", "sea", "ocean", "cloud", "clouds", "plant",
                "plants", "leaf", "leaves", "sky", "wind", "grass", "seed",
                "seeds")),
    ("food", ("eat", "eats", "eating", "food", "fruit", "fruits", "rice",
              "mango", "mangoes", "bread", "cook", "cooking", "kitchen",
              "hungry", "hunger", "meal", "sweet", "sweets", "milk")),
    ("feelings", ("afraid", "fear", "fears", "happy", "happiness", "sad",
                  "sadness", "angry", "anger", "cry", "crying", "cries",
                  "brave", "shy", "worried", "worry", "lonely", "laugh",
                  "laughs", "laughing", "smile", "smiles")),
    ("home", ("house", "houses", "home", "village", "door", "doors", "window",
              "windows", "room", "rooms", "roof", "street")),
    ("vehicles", ("car", "cars", "bus", "buses", "train", "trains", "boat",
                  "boats", "cycle", "bicycle", "truck", "trucks", "plane",
                  "aeroplane", "auto", "cart")),
    ("counting", ("count", "counts", "counting", "number", "numbers")),
    ("colors", ("red", "blue", "green", "yellow", "colour", "colours", "color",
                "colors", "paint", "paints", "purple", "orange", "pink")),
    ("community", ("doctor", "doctors", "police", "farmer", "farmers", "market",
                   "shop", "shops", "neighbour", "neighbor", "community",
                   "helper", "helpers")),
    ("adventure", ("adventure", "adventures", "journey", "journeys", "travel",
                   "travels", "trip", "trips", "explore", "explores", "lost")),
    ("body", ("body", "nose", "eyes", "ears", "hands", "feet", "hair", "teeth",
              "tooth", "fingers")),
    ("festivals", ("festival", "festivals", "diwali", "eid", "christmas",
                   "pongal", "holi", "celebrate", "celebration")),
)


def derive_themes(*texts: str | None) -> str:
    """Return up to two keyword-derived theme labels, or '' if nothing matches."""
    blob = " ".join(t.lower() for t in texts if t)
    blob = re.sub(r"[^a-z0-9\s]", " ", blob)
    scored: list[tuple[int, str]] = []
    for theme, words in THEME_KEYWORDS:
        score = 0
        for word in words:
            if re.search(r"\b" + re.escape(word) + r"\b", blob):
                score += 1
        if score:
            scored.append((score, theme))
    scored.sort(key=lambda pair: (-pair[0], pair[1]))
    return ", ".join(theme for _, theme in scored[:2])


def describe_drop(book: dict, reason: str) -> dict:
    return {
        "id": book.get("id"),
        "title": book.get("title") or "",
        "reads": reads_of(book),
        "reason": reason,
    }


# ---------------------------------------------------------------------------
# data gathering
# ---------------------------------------------------------------------------

def probe_levels_filter(fetcher: Fetcher) -> tuple[dict[str, int], bool | None]:
    """Compare metadata.hits for levels[]=1/2/3/4 vs unfiltered.

    Returns (hits_by_label, filters?) where filters is True if ``levels[]``
    visibly changes hits, False if it is ignored, None if undecidable.
    """
    hits: dict[str, int] = {}
    for level in ("1", "2", "3", "4"):
        payload = fetcher.get_json(search_url(1, 1, levels=[level]))
        hits[level] = int((payload.get("metadata") or {}).get("hits") or -1)
    payload = fetcher.get_json(search_url(1, 1, levels=None))
    hits["all"] = int((payload.get("metadata") or {}).get("hits") or -1)

    level_hits = [hits[k] for k in ("1", "2", "3", "4")]
    filters: bool | None
    if hits["all"] <= 0 or any(h < 0 for h in level_hits):
        filters = None
    elif all(h == hits["all"] for h in level_hits):
        filters = False  # param ignored: every level returns the full hit count
    elif len(set(level_hits)) > 1 and all(h <= hits["all"] for h in level_hits):
        filters = True
    else:
        filters = None
    return hits, filters


def collect_search_pool(fetcher: Fetcher, min_english: int) -> tuple[list[dict], dict]:
    """Page books-search (Most Read) until >= min_english English books, deduped."""
    requested = 100
    first = fetcher.get_json(search_url(1, requested))
    rows0 = first.get("data") or []
    hits = int((first.get("metadata") or {}).get("hits") or 0)

    # per_page=100 is "accepted" only if we actually get 100 rows while more
    # hits exist; otherwise the server capped the page size (e.g. at 24).
    if 0 < len(rows0) < requested and hits > len(rows0):
        per_page = len(rows0)
    else:
        per_page = requested

    pool: dict = {}

    def ingest(rows: list[dict]) -> None:
        for book in rows:
            book_id = book.get("id")
            if book_id is not None and book_id not in pool:
                pool[book_id] = book

    def english_count() -> int:
        return sum(1 for b in pool.values() if b.get("language") == "English")

    ingest(rows0)
    page = 1
    max_pages = MAX_SEARCH_PAGES
    if per_page > 0 and hits > 0:
        max_pages = min(MAX_SEARCH_PAGES, (min(hits, 10000) + per_page - 1) // per_page)

    while english_count() < min_english and page < max_pages:
        page += 1
        payload = fetcher.get_json(search_url(page, per_page))
        rows = payload.get("data") or []
        if not rows:
            break
        ingest(rows)

    notes = {"hits": hits, "per_page": per_page, "pages_fetched": page}
    return list(pool.values()), notes


def client_filter(books: list[dict]) -> tuple[list[dict], list[dict]]:
    """language == English, level in {1,2,3}, not a GIF.

    Returns (eligible, dropped) where dropped entries carry a drop reason.
    (The API caps hits at 10000 and honors params only partially, so this
    client-side pass is mandatory even when the query already filtered.)
    """
    eligible: list[dict] = []
    dropped: list[dict] = []
    for book in books:
        language = str(book.get("language") or "")
        level = level_of(book)
        if language != "English":
            dropped.append(describe_drop(book, f"language={language or '?'}"))
        elif is_gif(book):
            dropped.append(describe_drop(book, "gif"))
        elif level == "4":
            dropped.append(describe_drop(book, "level 4"))
        elif level not in ALLOWED_LEVELS:
            dropped.append(describe_drop(book, f"level={level or '?'}"))
        else:
            eligible.append(book)
    eligible.sort(key=reads_of, reverse=True)
    return eligible, dropped


def fetch_page_count(fetcher: Fetcher, book_id) -> int | None:
    """Per-story metadata: lastPagePosition is the book's page count."""
    try:
        payload = fetcher.get_json(story_url(book_id))
    except RuntimeError as err:
        print(f"  ! metadata failed for {book_id}: {err}", file=sys.stderr)
        return None
    data = payload.get("data") or {}
    try:
        return int(data.get("lastPagePosition"))
    except (TypeError, ValueError):
        return None


def apply_page_filter(
    fetcher: Fetcher,
    eligible: list[dict],
    meta_limit: int,
    final_target: int,
) -> tuple[list[dict], list[dict], int]:
    """Fetch page counts for the top-N by reads, keep MIN_PAGES..MAX_PAGES.

    Only the top ``meta_limit`` books (grown by META_FETCH_BATCH up to
    META_FETCH_HARD_CAP if the shortlist runs short) get a per-story metadata
    fetch -- page counts are not knowable any cheaper. Returns
    (finalists_in_reads_order, dropped_with_reason, metadata_fetches).
    """
    finalists: list[dict] = []
    dropped: list[dict] = []
    fetched = 0
    window = min(meta_limit, len(eligible))

    def inspect(book: dict) -> bool:
        """Fetch one book's page count; record finalist/drop. True if finalist."""
        nonlocal fetched
        pages = fetch_page_count(fetcher, book.get("id"))
        fetched += 1
        if pages is None:
            dropped.append(describe_drop(book, "page count unavailable"))
            return False
        if pages < MIN_PAGES:
            dropped.append(describe_drop(book, f"pages={pages} (under {MIN_PAGES})"))
            return False
        if pages > MAX_PAGES:
            dropped.append(describe_drop(book, f"pages={pages} (over {MAX_PAGES})"))
            return False
        book = dict(book)
        book["_pages"] = pages
        finalists.append(book)
        return True

    for book in eligible[:window]:
        inspect(book)

    while (
        len(finalists) < final_target
        and window < len(eligible)
        and window < max(meta_limit, META_FETCH_HARD_CAP)
    ):
        grow = min(META_FETCH_BATCH, len(eligible) - window)
        grow = min(grow, max(meta_limit, META_FETCH_HARD_CAP) - window)
        if grow <= 0:
            break
        for book in eligible[window : window + grow]:
            inspect(book)
        window += grow

    return finalists, dropped, fetched


# ---------------------------------------------------------------------------
# output
# ---------------------------------------------------------------------------

def candidate_record(book: dict) -> dict:
    slug = str(book.get("slug") or "")
    return {
        "id": book.get("id"),
        "title": book.get("title") or "",
        "slug": slug,
        "level": level_of(book),
        "pages": book.get("_pages"),
        "reads": reads_of(book),
        "likes": likes_of(book),
        "editorsPick": bool(book.get("editorsPick")),
        "recommended": bool(book.get("recommended")),
        "authors": name_list(book.get("authors")),
        "illustrators": name_list(book.get("illustrators")),
        # verbatim from the API -- curation happens in the MD themes column only
        "description": book.get("description") or "",
        "coverThumbUrl": cover_thumb_url(book),
        "sourceUrl": f"{SITE_BASE}/en/stories/{slug}" if slug else None,
    }


def build_markdown(records: list[dict], notable: list[dict]) -> str:
    lines: list[str] = []
    lines.append("# StoryWeaver book candidates")
    lines.append("")
    lines.append(
        "Curation shortlist for the in-game library shelf (pick 18). "
        "Source: StoryWeaver / Pratham Books, CC BY 4.0 (attribution required). "
        "Sorted by reads (Most Read)."
    )
    lines.append("")
    lines.append(
        "| id | level | pages | reads | title | author | description | themes |"
    )
    lines.append(
        "| ---: | :---: | ---: | ---: | :--- | :--- | :--- | :--- |"
    )
    for rec in records:
        authors = ", ".join(rec["authors"]) or (", ".join(rec["illustrators"]) or "—")
        themes = derive_themes(rec.get("title"), rec.get("description"))
        desc = one_line(rec.get("description"))
        lines.append(
            "| {id} | {level} | {pages} | {reads} | {title} | {author} | {desc} | {themes} |".format(
                id=rec["id"],
                level=rec["level"],
                pages=rec["pages"],
                reads="{:,}".format(rec["reads"]),
                title=md_cell(rec["title"]) or "—",
                author=md_cell(authors),
                desc=md_cell(desc) or "—",
                themes=md_cell(themes) or "—",
            )
        )

    lines.append("")
    lines.append("## Excluded notable titles")
    lines.append("")
    if notable:
        lines.append("High-read titles dropped by the curation filters:")
        lines.append("")
        lines.append("| id | reads | title | reason |")
        lines.append("| ---: | ---: | :--- | :--- |")
        for item in notable:
            lines.append(
                "| {id} | {reads} | {title} | {reason} |".format(
                    id=item["id"],
                    reads="{:,}".format(item["reads"]),
                    title=md_cell(item["title"]) or "—",
                    reason=md_cell(item["reason"]),
                )
            )
    else:
        lines.append("_none_")
    lines.append("")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# subcommand: candidates
# ---------------------------------------------------------------------------

def cmd_candidates(args: argparse.Namespace) -> int:
    fetcher = Fetcher(use_cache=not args.no_cache)

    print("== fetch_books.py candidates ==", file=sys.stderr)

    # 1) does levels[] actually filter? (we still filter client-side regardless)
    hits, filters = probe_levels_filter(fetcher)
    filters_label = {True: "filters server-side", False: "is IGNORED", None: "undecidable"}[filters]
    probe_line = (
        "levels[] probe: hits level1={h1} level2={h2} level3={h3} level4={h4} "
        "all={hall} -> levels[] {label}"
    ).format(
        h1=hits["1"], h2=hits["2"], h3=hits["3"], h4=hits["4"],
        hall=hits["all"], label=filters_label,
    )
    print(probe_line, file=sys.stderr)

    # 2) assemble the search pool (>= TARGET_ENGLISH English, deduped by id)
    pool, notes = collect_search_pool(fetcher, args.min_english)
    english = sum(1 for b in pool if b.get("language") == "English")
    print(
        "search: {pages} pages (per_page={pp}), hits={hits}, collected={n} "
        "({eng} English, deduped)".format(
            pages=notes["pages_fetched"],
            pp=notes["per_page"],
            hits=notes["hits"],
            n=len(pool),
            eng=english,
        ),
        file=sys.stderr,
    )

    # 3) client-side filters
    eligible, dropped = client_filter(pool)
    client_dropped = len(dropped)
    print(
        f"client filter: eligible={len(eligible)}, dropped={client_dropped}",
        file=sys.stderr,
    )

    # 4) page-count window: metadata for the top ~60 by reads, then 6..20 pages
    finalists, page_dropped, meta_fetches = apply_page_filter(
        fetcher, eligible, args.meta_limit, args.final_target
    )
    dropped.extend(page_dropped)
    inspected = min(args.meta_limit, len(eligible))
    uninspected = [
        describe_drop(b, f"below top-{inspected} by reads (page count not fetched)")
        for b in eligible[inspected:]
    ]
    print(
        f"page-count window: metadata fetches={meta_fetches}, "
        f"{MIN_PAGES}..{MAX_PAGES} pages -> {len(finalists)} finalists "
        f"({len(uninspected)} uninspected, lower reads)",
        file=sys.stderr,
    )

    records = [candidate_record(b) for b in finalists]  # already reads-desc

    # 5) markdown: table + notable exclusions (causal drops only, high reads first)
    notable = sorted(
        (d for d in dropped if "below top-" not in d["reason"]),
        key=lambda d: d["reads"],
        reverse=True,
    )[:NOTABLE_LIMIT]
    markdown = build_markdown(records, notable)

    JSON_OUT.write_text(json.dumps(records, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    MD_OUT.write_text(markdown, encoding="utf-8")

    # 6) stdout: compact summary + full markdown table for the PM
    level_counts: dict[str, int] = {}
    for rec in records:
        level_counts[rec["level"]] = level_counts.get(rec["level"], 0) + 1
    level_summary = "  ".join(
        f"{lv}={level_counts.get(lv, 0)}" for lv in sorted(level_counts)
    )
    print(f"levels[] probe     : {probe_line}")
    print(
        "search pool        : {n} books ({eng} English) from {pages} pages "
        "(hits={hits}, per_page={pp})".format(
            n=len(pool),
            eng=english,
            pages=notes["pages_fetched"],
            hits=notes["hits"],
            pp=notes["per_page"],
        )
    )
    print(f"client filter      : eligible={len(eligible)}  dropped={client_dropped}")
    print(f"metadata fetches   : {meta_fetches} (page counts for top by reads)")
    print(
        f"page-count filter  : dropped={len(page_dropped)} "
        f"({MIN_PAGES}..{MAX_PAGES} pages window)"
    )
    print(f"final candidates   : {len(records)}   by level: {level_summary}")
    print(f"bytes fetched      : {fetcher.stats()}")
    print(f"wrote              : {JSON_OUT}  ({len(records)} candidates)")
    print(f"wrote              : {MD_OUT}")
    print()
    print(markdown)
    return 0


# ---------------------------------------------------------------------------
# subcommand: download
# ---------------------------------------------------------------------------

LIBRARY_DEFAULT = Path(__file__).resolve().parent.parent / "library" / "books"

XHR_HEADERS = {
    "Accept": "text/javascript, application/javascript, */*",
    "X-Requested-With": "XMLHttpRequest",
}

LICENSE = "CC BY 4.0"
LICENSE_URL = "https://creativecommons.org/licenses/by/4.0/"

# Attribution / credits blocks inside the pages payload (CC BY compliance).
CREDIT_CLASSES = frozenset(
    {
        "attrb-full",
        "attribution-text",
        "story-attribution-section",
        "other-credits-section",
        "illustration-attributions-section",
    }
)

JPEG_MAGIC = b"\xff\xd8"
JPEG_MIN_BYTES = 2048  # "every JPEG starts with FFD8 and > 2KB"

# reimage cap: "300KB" in the 1 KB = 1024 B convention of JPEG_MIN_BYTES above
REIMAGE_MAX_BYTES = 300 * 1024
REIMAGE_LADDER = ("size7", "size6", "size5")

SIZE_SRC_KEYS = (
    "data-size7-src",
    "data-size6-src",
    "data-size5-src",
    "data-size4-src",
    "data-size3-src",
    "data-size2-src",
    "data-size1-src",
)


def class_tokens(tag: str) -> set[str]:
    m = re.search(r"""class\s*=\s*['"]([^'"]*)['"]""", tag)
    return set(m.group(1).split()) if m else set()


def extract_reader_html(payload: str) -> str:
    """Pull the HTML out of ``$('#storyReader').html("...")`` and JS-unescape it.

    Verified escape recipe (order matters): ``\\"`` first, then ``\\'``, then
    ``\\/`` -- ONLY THEN run HTML regexes over the result.
    """
    m = re.search(r"\.html\(\s*\"", payload)
    if not m:
        raise RuntimeError("pages payload: $('#storyReader').html(\"...\") wrapper not found")
    start = m.end()
    # scan to the closing unescaped double quote of the JS string
    j = start
    while j < len(payload):
        if payload[j] == "\\":
            j += 2
            continue
        if payload[j] == '"':
            break
        j += 1
    content = payload[start:j]
    content = content.replace(r"\"", '"').replace(r"\'", "'").replace(r"\/", "/")
    return content


def element_inner_span(doc: str, open_end: int, is_div: bool) -> tuple[int, int]:
    """(start, end) of the inner HTML of the element whose open tag ends at open_end."""
    if is_div:
        depth = 1
        for t in re.finditer(r"<div\b[^>]*>|</div>", doc[open_end:]):
            if t.group(0).startswith("</"):
                depth -= 1
                if depth == 0:
                    return open_end, open_end + t.start()
            else:
                depth += 1
        return open_end, len(doc)
    end = doc.find("</p>", open_end)
    return open_end, (end if end != -1 else len(doc))


def strip_tags(fragment: str) -> str:
    """Tags stripped + html.unescape + whitespace collapsed (text extraction)."""
    fragment = re.sub(r"(?is)<(script|style)\b.*?</\1>", " ", fragment)
    # keep word gaps where block-level tags used to sit
    fragment = re.sub(r"(?i)</?(p|div|br|li|tr|h[1-6])\b[^>]*>", " ", fragment)
    fragment = re.sub(r"<[^>]+>", "", fragment)
    return re.sub(r"\s+", " ", html.unescape(fragment)).strip()


def drop_nested_spans(spans: list[tuple[int, int, str]]) -> list[tuple[int, int, str]]:
    """Keep outermost (start, end, text) spans only, in document order."""
    kept: list[tuple[int, int, str]] = []
    for start, end, text in sorted(spans, key=lambda c: (c[0], -c[1])):
        if any(s <= start and end <= e for s, e, _ in kept):
            continue
        kept.append((start, end, text))
    kept.sort(key=lambda c: c[0])
    return kept


def split_page_containers(html_doc: str) -> list[str]:
    """Split the reader HTML into its ``story-page`` containers (payload order)."""
    starts = [m.start() for m in re.finditer(
        r"<div\b[^>]*class=['\"][^'\"]*\bstory-page\b[^'\"]*['\"][^>]*>", html_doc
    )]
    spans = [(starts[i], starts[i + 1] if i + 1 < len(starts) else len(html_doc))
             for i in range(len(starts))]
    return [html_doc[a:b] for a, b in spans]


def container_content_texts(container: str) -> str:
    """Textbox text of one page: every ``content``/``newStories`` div joined with a space."""
    spans: list[tuple[int, int, str]] = []
    for m in re.finditer(r"<div\b[^>]*>", container):
        toks = class_tokens(m.group(0))
        if "content" not in toks and "newStories" not in toks:
            continue
        a, b = element_inner_span(container, m.end(), True)
        spans.append((a, b, strip_tags(container[a:b])))
    texts = [t for _, _, t in drop_nested_spans(spans)]
    return re.sub(r"\s+", " ", " ".join(texts)).strip()


def container_image_url(container: str) -> str | None:
    """size7 image url of one page block (falls back to smaller sizes)."""
    for m in re.finditer(r"<img\b[^>]*>", container):
        tag = m.group(0)
        if "responsive_illustration" not in class_tokens(tag):
            continue
        for key in SIZE_SRC_KEYS:
            am = re.search(re.escape(key) + r"""\s*=\s*['"]([^'"]+)['"]""", tag)
            if am:
                return am.group(1)
        am = re.search(r"""(?<![\w-])src\s*=\s*['"]([^'"]+)['"]""", tag)
        if am:
            return am.group(1)
    return None


def container_image_size_urls(container: str) -> dict[str, str]:
    """``sizeN`` -> url for one page block's ``responsive_illustration`` img.

    All ``data-sizeN-src`` ladder steps the payload carries (usually size1..7);
    empty dict for a numbered text-only page (no illustration).
    """
    out: dict[str, str] = {}
    for m in re.finditer(r"<img\b[^>]*>", container):
        tag = m.group(0)
        if "responsive_illustration" not in class_tokens(tag):
            continue
        for key in SIZE_SRC_KEYS:
            am = re.search(re.escape(key) + r"""\s*=\s*['"]([^'"]+)['"]""", tag)
            if am:
                out[key[len("data-") : -len("-src")]] = am.group(1)
        if out:
            return out
    return out


def size_variant_url(url: str, step: str) -> str | None:
    """Same crop hash, different ladder step: ``.../size7/{hash}.jpg`` -> ``step``.

    Returns None when the url carries no ``/sizeN/`` ladder segment.
    """
    if not re.search(r"/size[1-7]/", url):
        return None
    return re.sub(r"/size[1-7]/", f"/{step}/", url)


def container_is_story_page(container: str) -> bool:
    """True for numbered book pages (``fc_`` front cover / ``sp_`` story pages).

    ``bic_`` (credits / back-inside-cover) and ``bc_`` (back cover) blocks are
    unnumbered end-matter: the payload's own ``page_number`` divs number only
    fc/sp pages (``2/10`` ... ``10/10``, front cover implied as page 1) and
    metadata ``lastPagePosition`` counts exactly those.
    """
    m = re.search(r"""class=['"]((?:fc|sp|bic|bc)_)""", container)
    if m:
        return m.group(1) in ("fc_", "sp_")
    return bool(re.search(r"""class=["'][^"']*\bpage_number\b""", container))


def extract_attribution(html_doc: str) -> str:
    """Verbatim (tags stripped) credits text from the payload's attribution blocks."""
    spans: list[tuple[int, int, str]] = []
    for m in re.finditer(r"<(?:div|p)\b[^>]*>", html_doc):
        tag = m.group(0)
        if not (class_tokens(tag) & CREDIT_CLASSES):
            continue
        is_div = tag.startswith("<div")
        a, b = element_inner_span(html_doc, m.end(), is_div)
        spans.append((a, b, strip_tags(html_doc[a:b])))
    texts: list[str] = []
    seen: set[str] = set()
    for _, _, text in drop_nested_spans(spans):
        if text and text not in seen:
            seen.add(text)
            texts.append(text)
    return re.sub(r"\s+", " ", " ".join(texts)).strip()


def parse_published_year(
    attribution: str, copyright_notice: str, published_date: str
) -> tuple[str, str]:
    """(year, source) for ``publishedYear``.

    The rule is the credits' ``© Pratham Books, YYYY`` line (the metadata
    copyrightNotice field is yearless on StoryWeaver; the © line lives in the
    attribution blocks). Some books credit other rightsholders
    (``© Room to Read, YYYY``, ``The © for this translation lies with ...``),
    so the © holder is matched loosely -- the year CC BY requires displaying
    must be the year stored in ``publishedYear``. Falls back to publishedDate.
    """
    pratham = re.compile(r"©\s*Pratham\s*Books[^0-9]{0,20}((?:19|20)\d{2})")
    any_holder = re.compile(r"©[^0-9]{0,60}((?:19|20)\d{2})")
    for pat, label in ((pratham, "© Pratham Books line"), (any_holder, "© line")):
        for text, where in ((copyright_notice, "copyrightNotice"), (attribution, "attribution")):
            m = pat.search(text or "")
            if m:
                return m.group(1), f"{label} in {where}"
    m = re.search(r"\b((?:19|20)\d{2})\b", published_date or "")
    if m:
        return m.group(1), "publishedDate"
    return "", "none"


def valid_jpeg(path: Path) -> bool:
    try:
        data = path.read_bytes()
    except OSError:
        return False
    return data.startswith(JPEG_MAGIC) and len(data) > JPEG_MIN_BYTES


def parse_id_list(raw: str) -> list[int]:
    out: list[int] = []
    for part in raw.replace(" ", "").split(","):
        if part:
            out.append(int(part))
    return out


def book_complete(book_dir: Path) -> bool:
    """Resume marker: book.json present and every JPEG it references is valid."""
    bj_path = book_dir / "book.json"
    if not bj_path.exists():
        return False
    try:
        data = json.loads(bj_path.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return False
    pages = data.get("pages") or []
    if not pages or len(pages) != data.get("pageCount"):
        return False
    if not valid_jpeg(book_dir / "thumb.jpg"):
        return False
    for page in pages:
        image = str(page.get("image") or "")
        if image and not valid_jpeg(book_dir / image):
            return False
    return True


def cover_page_href(fetcher: Fetcher, book_id) -> str:
    """The show-in-iframe HTML's ``/en/v0/stories/{slug}/pages/{pageId}`` href."""
    iframe = fetcher.get_text(f"{SITE_BASE}/stories/show-in-iframe/{book_id}")
    m = re.search(r"""href=['"](/en/v0/stories/[^'"]+/pages/\d+)['"]""", iframe)
    if not m:
        raise RuntimeError(f"no pages href in show-in-iframe for {book_id}")
    return m.group(1)


def page_source_urls(fetcher: Fetcher, book_id) -> list[dict[str, str]]:
    """Per numbered page (book order): ``sizeN`` -> image url from the payload.

    Same parse chain as :func:`download_book`, one cached XHR per book. Text-only
    numbered pages yield ``{}`` (no illustration). End-matter blocks (credits /
    back-cover art) are excluded exactly as during download.
    """
    href = cover_page_href(fetcher, book_id)
    raw = fetcher.get_text(f"{SITE_BASE}{href}", headers=XHR_HEADERS)
    html_doc = extract_reader_html(raw)
    out: list[dict[str, str]] = []
    for container in split_page_containers(html_doc):
        if not container_is_story_page(container):
            continue
        out.append(container_image_size_urls(container))
    return out


def download_jpeg(fetcher: Fetcher, url: str, dest: Path) -> None:
    """Fetch one image unless dest already holds a valid JPEG (resume-tolerant)."""
    if valid_jpeg(dest):
        return
    dest.write_bytes(fetcher.get_bytes(url))


def download_book(
    fetcher: Fetcher,
    book_id: int,
    shelf_order: int,
    out_root: Path,
    meta_lpp: dict[int, int | None],
) -> dict:
    """Ingest one book. Returns the report row dict (also used by validation)."""
    book_dir = out_root / str(book_id)
    warnings: list[str] = []

    # 1) metadata (always fetched -- page-count validation needs lastPagePosition)
    data = fetcher.get_json(story_url(book_id)).get("data") or {}
    try:
        meta_lpp[book_id] = int(data.get("lastPagePosition"))
    except (TypeError, ValueError):
        meta_lpp[book_id] = None

    if book_complete(book_dir):
        existing = json.loads((book_dir / "book.json").read_text(encoding="utf-8"))
        text_pages = sum(1 for p in existing.get("pages") or [] if (p.get("text") or "").strip())
        return {
            "id": book_id,
            "title": existing.get("title") or "",
            "pages": existing.get("pageCount") or 0,
            "bytes": sum(p.stat().st_size for p in sorted(book_dir.iterdir()) if p.is_file()),
            "text_pages": text_pages,
            "skipped": True,
            "warnings": warnings,
        }

    book_dir.mkdir(parents=True, exist_ok=True)

    # 2) cover page id + 3) the one XHR payload with every page
    href = cover_page_href(fetcher, book_id)
    raw = fetcher.get_text(f"{SITE_BASE}{href}", headers=XHR_HEADERS)
    html_doc = extract_reader_html(raw)

    # 4) split into page blocks; keep the NUMBERED pages (fc front cover +
    #    sp story pages) == metadata lastPagePosition == the payload's own
    #    page_number "N/M" sequence. bic/bc credits + back-cover blocks are
    #    unnumbered end-matter: their text is preserved VERBATIM in
    #    `attribution` (and is not part of pages[]).
    containers = split_page_containers(html_doc)
    pages: list[dict] = []
    end_matter = 0
    end_matter_imaged = 0
    text_only_pages: list[int] = []
    for container in containers:
        if not container_is_story_page(container):
            end_matter += 1
            if container_image_url(container):
                end_matter_imaged += 1
            continue
        img_url = container_image_url(container)
        n = len(pages) + 1
        if img_url is None:
            # numbered text-only page (payload has no illustration for it)
            text_only_pages.append(n)
        pages.append(
            {
                "n": n,
                "image": f"page-{n:02d}.jpg" if img_url else "",
                "text": container_content_texts(container),
                "_url": img_url,
            }
        )
    if not pages:
        raise RuntimeError(f"{book_id}: no numbered pages found in payload")
    if end_matter:
        warnings.append(
            f"{end_matter} credits/back-cover end-matter block(s) captured in attribution "
            f"(not numbered pages)"
        )
    if end_matter_imaged:
        warnings.append(
            f"{end_matter_imaged} end-matter block(s) carry an illustration in the payload "
            f"(back-cover art, not a numbered page; not downloaded)"
        )
    for n in text_only_pages:
        warnings.append(f"page {n} is a numbered text-only page (no image in payload)")

    # 5) attribution (verbatim credits, tags stripped) + year
    attribution = extract_attribution(html_doc)
    copyright_notice = str(data.get("copyrightNotice") or "")
    published_year, year_src = parse_published_year(
        attribution, copyright_notice, str(data.get("publishedDate") or "")
    )
    if not published_year:
        warnings.append("publishedYear unavailable")

    # 6) images: thumb + page-NN.jpg (size7), skipping already-valid files
    thumb_url = cover_thumb_url(data)
    if thumb_url:
        download_jpeg(fetcher, thumb_url, book_dir / "thumb.jpg")
    else:
        warnings.append("no cover thumb url in metadata")
    for page in pages:
        if page["_url"]:
            download_jpeg(fetcher, page["_url"], book_dir / page["image"])
    # drop stale page images left over from a previous (differently-parsed) run
    referenced = {p["image"] for p in pages if p["image"]} | {"thumb.jpg"}
    for stale in sorted(book_dir.glob("page-*.jpg")):
        if stale.name not in referenced:
            stale.unlink()

    # 7) book.json (exact schema)
    slug = str(data.get("slug") or "")
    book_json = {
        "id": int(book_id),
        "title": str(data.get("name") or ""),
        "slug": slug,
        "sourceUrl": f"{SITE_BASE}/en/stories/{slug}",
        "language": str(data.get("language") or ""),
        "level": int(data.get("level") or 0),
        "orientation": str(data.get("orientation") or ""),
        "pageCount": len(pages),
        "license": LICENSE,
        "licenseUrl": LICENSE_URL,
        "attribution": attribution,
        "copyrightNotice": copyright_notice,
        "publisher": str((data.get("publisher") or {}).get("name") or ""),
        "publishedYear": published_year,
        "authors": name_list(data.get("authors")),
        "illustrators": name_list(data.get("illustrators")),
        "shelfOrder": shelf_order,
        "pages": [{"n": p["n"], "image": p["image"], "text": p["text"]} for p in pages],
    }
    (book_dir / "book.json").write_text(
        json.dumps(book_json, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
    )

    text_pages = sum(1 for p in pages if p["text"])
    return {
        "id": book_id,
        "title": book_json["title"],
        "pages": len(pages),
        "bytes": sum(p.stat().st_size for p in sorted(book_dir.iterdir()) if p.is_file()),
        "text_pages": text_pages,
        "skipped": False,
        "warnings": warnings,
    }


def validate_library(
    out_root: Path,
    rows: list[dict],
    meta_lpp: dict[int, int | None],
) -> tuple[list[str], list[str]]:
    """Full validation pass. Returns (errors, warnings); errors => fail loudly."""
    errors: list[str] = []
    warnings: list[str] = []
    for row in rows:
        book_id = row["id"]
        book_dir = out_root / str(book_id)
        label = f"book {book_id}"
        try:
            data = json.loads((book_dir / "book.json").read_text(encoding="utf-8"))
        except (OSError, ValueError) as err:
            errors.append(f"{label}: book.json unreadable: {err}")
            continue

        pages = data.get("pages") or []
        page_count = data.get("pageCount")
        # pageCount == number of pages; image files == pages that reference one
        images_on_disk = sorted(book_dir.glob("page-*.jpg"))
        referenced = [str(p.get("image") or "") for p in pages]
        referenced_files = [r for r in referenced if r]
        if page_count != len(pages):
            errors.append(f"{label}: pageCount {page_count} != {len(pages)} pages in book.json")
        if len(referenced_files) != len(images_on_disk):
            errors.append(
                f"{label}: {len(referenced_files)} image refs in book.json != "
                f"{len(images_on_disk)} page-*.jpg on disk"
            )
        lpp = meta_lpp.get(book_id)
        if lpp is not None and page_count != lpp:
            errors.append(f"{label}: pageCount {page_count} != metadata lastPagePosition {lpp}")

        # every JPEG: FFD8 magic + > 2KB (thumb + referenced pages)
        jpegs = [book_dir / "thumb.jpg"] + [book_dir / r for r in referenced_files]
        for jpg in jpegs:
            if not jpg.exists():
                errors.append(f"{label}: missing {jpg.name}")
            elif not jpg.read_bytes().startswith(JPEG_MAGIC):
                errors.append(f"{label}: {jpg.name} does not start with FFD8")
            elif jpg.stat().st_size <= JPEG_MIN_BYTES:
                errors.append(f"{label}: {jpg.name} is <= 2KB ({jpg.stat().st_size} bytes)")

        # attribution: non-empty + license-aware wording + the year
        attribution = str(data.get("attribution") or "")
        year = str(data.get("publishedYear") or "")
        license_name = str(data.get("license") or "")
        if not attribution.strip():
            errors.append(f"{label}: attribution is empty")
        else:
            if license_name.startswith("CC BY"):
                if "CC BY" not in attribution:
                    errors.append(f"{label}: attribution does not contain 'CC BY'")
            elif license_name == "Public Domain":
                if "public domain" not in attribution.lower():
                    errors.append(f"{label}: attribution does not contain 'public domain'")
            else:
                errors.append(f"{label}: unsupported license {license_name!r}")
            if not year:
                errors.append(f"{label}: publishedYear is missing")
            elif year not in attribution:
                errors.append(f"{label}: attribution does not contain the year {year}")

        # at least 4 pages of non-empty text (report-only)
        text_pages = sum(1 for p in pages if (p.get("text") or "").strip())
        if text_pages < 4:
            warnings.append(f"{label} ({data.get('title')}): only {text_pages} page(s) with text")
    return errors, warnings


def print_report(rows: list[dict], errors: list[str], warnings: list[str]) -> None:
    total_pages = sum(r["pages"] for r in rows)
    total_bytes = sum(r["bytes"] for r in rows)
    total_text = sum(r["text_pages"] for r in rows)
    mb = total_bytes / (1024.0 * 1024.0)

    print()
    print("== fetch_books.py download -- final report ==")
    print()
    print("| id | title | pages | bytes | text pages |")
    print("| ---: | :--- | ---: | ---: | ---: |")
    for row in rows:
        flag = " (resumed)" if row.get("skipped") else ""
        print(
            "| {id} | {title}{flag} | {pages} | {bytes:,} | {text} |".format(
                id=row["id"],
                title=(row["title"] or "?").replace("|", "\\|"),
                flag=flag,
                pages=row["pages"],
                bytes=row["bytes"],
                text=row["text_pages"],
            )
        )
    print("| | **TOTAL** | **{pages}** | **{bytes:,}** ({mb:.2f} MiB) | **{text}** |".format(
        pages=total_pages, bytes=total_bytes, mb=mb, text=total_text
    ))
    print()
    print(f"totals: {len(rows)} books, {total_pages} pages, "
          f"{total_bytes:,} bytes ({mb:.2f} MiB), {total_text} text pages")

    all_warnings = [w for row in rows for w in row.get("warnings") or []] + warnings
    if all_warnings:
        print()
        print("warnings:")
        for w in all_warnings:
            print(f"  - {w}")
    else:
        print("warnings: none")

    print()
    if errors:
        print(f"VALIDATION FAILED ({len(errors)} error(s)):")
        for err in errors:
            print(f"  ! {err}")
    else:
        print("validation: OK (JPEG magic+size, page counts vs lastPagePosition, "
              "attribution CC BY + year, text-page floor)")


def cmd_download(args: argparse.Namespace) -> int:
    ids = parse_id_list(args.ids)
    if not ids:
        print("error: --ids produced an empty id list", file=sys.stderr)
        return 2
    out_root = Path(args.out)
    out_root.mkdir(parents=True, exist_ok=True)

    fetcher = Fetcher(use_cache=not args.no_cache)
    print(f"== fetch_books.py download: {len(ids)} books -> {out_root} ==", file=sys.stderr)

    rows: list[dict] = []
    meta_lpp: dict[int, int | None] = {}
    for shelf_order, book_id in enumerate(ids, start=1):
        print(f"[{shelf_order:02d}/{len(ids):02d}] book {book_id} ...",
              end=" ", file=sys.stderr, flush=True)
        try:
            row = download_book(fetcher, book_id, shelf_order, out_root, meta_lpp)
        except Exception as err:  # keep going; validation reports the hole loudly
            meta_lpp.setdefault(book_id, None)
            row = {
                "id": book_id,
                "title": f"FAILED: {err}",
                "pages": 0,
                "bytes": 0,
                "text_pages": 0,
                "skipped": False,
                "warnings": [f"download failed: {err}"],
            }
            print("FAILED", file=sys.stderr)
        else:
            state = "resumed" if row["skipped"] else f"{row['pages']} pages, {row['bytes']:,} B"
            print(state, file=sys.stderr)
        row["shelfOrder"] = shelf_order
        rows.append(row)

    # ordered shelf index (raw; the manifest task comes later)
    index = []
    for row in rows:
        bj_path = out_root / str(row["id"]) / "book.json"
        if not bj_path.exists():
            continue
        try:
            data = json.loads(bj_path.read_text(encoding="utf-8"))
        except (OSError, ValueError):
            continue
        index.append(
            {
                "id": data.get("id"),
                "shelfOrder": row["shelfOrder"],
                "title": data.get("title"),
                "level": data.get("level"),
                "pageCount": data.get("pageCount"),
                "path": str(row["id"]),
            }
        )
    (out_root / "index.json").write_text(
        json.dumps(index, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
    )

    errors, warnings = validate_library(out_root, rows, meta_lpp)
    for row in rows:
        if not (out_root / str(row["id"]) / "book.json").exists():
            errors.append(f"book {row['id']}: download failed, no book.json")

    print_report(rows, errors, warnings)
    print(f"bytes fetched      : {fetcher.stats()}")
    return 1 if errors else 0


# ---------------------------------------------------------------------------
# subcommand: reimage
# ---------------------------------------------------------------------------

def file_digest(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def reimage_book(fetcher: Fetcher, book_dir: Path) -> dict:
    """Downgrade this book's oversized page JPEGs via the CDN ladder.

    Only ``page-*.jpg`` files referenced by ``book.json`` and larger than
    ``REIMAGE_MAX_BYTES`` are candidates; everything else is never written.
    Returns the report row (before/after bytes + per-step counters).
    """
    warnings: list[str] = []
    book_id = int(book_dir.name) if book_dir.name.isdigit() else book_dir.name
    meta = json.loads((book_dir / "book.json").read_text(encoding="utf-8"))
    pages = meta.get("pages") or []
    before_bytes = sum(p.stat().st_size for p in sorted(book_dir.iterdir()) if p.is_file())

    # Public-domain (Project Gutenberg) books have no StoryWeaver CDN sources;
    # never resolve their ids against storyweaver.org.in.
    if str(meta.get("license") or "") != LICENSE:
        return {
            "id": book_id,
            "title": str(meta.get("title") or ""),
            "pages": len(pages),
            "before_bytes": before_bytes,
            "after_bytes": before_bytes,
            "over": 0,
            "to_size6": 0,
            "to_size5": 0,
            "still_over": 0,
            "kept_same": 0,
            "changed": [],
            "warnings": [
                "skipped: not a StoryWeaver (CC BY 4.0) book — no CDN sources"
            ],
        }

    # per-page size7..size1 urls from the (cached) one-call pages payload
    urls: list[dict[str, str]] | None
    try:
        urls = page_source_urls(fetcher, book_id)
    except Exception as err:  # keep the book untouched on any payload problem
        warnings.append(f"pages payload unavailable ({err}); book not re-imaged")
        urls = None
    if urls is not None and len(urls) != len(pages):
        warnings.append(
            f"payload has {len(urls)} numbered pages != book.json {len(pages)}; "
            f"book not re-imaged"
        )
        urls = None

    over = to_size6 = to_size5 = still_over = kept_same = 0
    changed: list[str] = []
    for page in pages:
        image = str(page.get("image") or "")
        if not image:
            continue  # numbered text-only page (e.g. book 7's page 9) -- no file
        dest = book_dir / image
        if not dest.exists():
            warnings.append(f"{image}: referenced by book.json but missing on disk")
            continue
        current = dest.read_bytes()
        if len(current) <= REIMAGE_MAX_BYTES:
            continue  # under the cap: never touched (old-era size7 is fine as-is)
        over += 1
        if urls is None:
            continue
        try:
            idx = int(page.get("n") or 0) - 1
        except (TypeError, ValueError):
            idx = -1
        sizes = urls[idx] if 0 <= idx < len(urls) else {}
        src = sizes.get("size7") or sizes.get("size6") or sizes.get("size5") or ""
        if not src:
            warnings.append(f"{image}: over cap but no source url in the payload")
            continue

        # Per-page rule: start at size7 (== current bytes, already known over the
        # cap here); drop to size6 while the result would exceed 300KB; floor at
        # size5 -- keep size5 (and warn) even if it is still over 300KB.
        variant_label = "size7"
        variant = current
        for label in REIMAGE_LADDER[1:]:
            vurl = sizes.get(label) or size_variant_url(src, label)
            if vurl is None:
                warnings.append(f"{image}: cannot derive a {label} url from {src}")
                break
            blob = fetcher.get_bytes(vurl)
            variant_label, variant = label, blob
            if len(blob) <= REIMAGE_MAX_BYTES:
                break
        if variant_label == "size7":
            kept_same += 1  # ladder derivation failed; nothing fetched
            continue
        if len(variant) > REIMAGE_MAX_BYTES:
            still_over += 1
            warnings.append(
                f"{image}: still over 300KB at {variant_label} "
                f"({len(variant):,} bytes); kept {variant_label}"
            )
        if not (variant.startswith(JPEG_MAGIC) and len(variant) > JPEG_MIN_BYTES):
            warnings.append(f"{image}: {variant_label} variant is not a valid JPEG; kept current bytes")
            kept_same += 1
            continue
        if len(variant) >= len(current):
            warnings.append(f"{image}: {variant_label} variant not smaller; kept current bytes")
            kept_same += 1
            continue
        dest.write_bytes(variant)  # same filename, same crop, smaller ladder step
        changed.append(image)
        if variant_label == "size6":
            to_size6 += 1
        else:
            to_size5 += 1

    after_bytes = sum(p.stat().st_size for p in sorted(book_dir.iterdir()) if p.is_file())
    return {
        "id": book_id,
        "title": str(meta.get("title") or ""),
        "pages": len(pages),
        "before_bytes": before_bytes,
        "after_bytes": after_bytes,
        "over": over,
        "to_size6": to_size6,
        "to_size5": to_size5,
        "still_over": still_over,
        "kept_same": kept_same,
        "changed": changed,
        "warnings": warnings,
    }


def print_reimage_report(
    rows: list[dict],
    errors: list[str],
    warnings: list[str],
    confirmations: dict,
) -> None:
    def mib(n: int) -> str:
        return f"{n / (1024.0 * 1024.0):.2f}"

    before_total = sum(r["before_bytes"] for r in rows)
    after_total = sum(r["after_bytes"] for r in rows)
    total_pages = sum(r["pages"] for r in rows)
    total_over = sum(r["over"] for r in rows)
    total_s6 = sum(r["to_size6"] for r in rows)
    total_s5 = sum(r["to_size5"] for r in rows)
    total_still = sum(r["still_over"] for r in rows)
    total_kept = sum(r["kept_same"] for r in rows)

    print()
    print("== fetch_books.py reimage -- final report ==")
    print()
    print("| id | title | pages | before MiB | after MiB | over 300KB | size6 | size5 |")
    print("| ---: | :--- | ---: | ---: | ---: | ---: | ---: | ---: |")
    for row in rows:
        print(
            "| {id} | {title} | {pages} | {before} | {after} | {over} | {s6} | {s5} |".format(
                id=row["id"],
                title=(row["title"] or "?").replace("|", "\\|"),
                pages=row["pages"],
                before=mib(row["before_bytes"]),
                after=mib(row["after_bytes"]),
                over=row["over"],
                s6=row["to_size6"],
                s5=row["to_size5"],
            )
        )
    print(
        "| | **TOTAL** | **{pages}** | **{before}** | **{after}** | **{over}** | **{s6}** | **{s5}** |".format(
            pages=total_pages,
            before=mib(before_total),
            after=mib(after_total),
            over=total_over,
            s6=total_s6,
            s5=total_s5,
        )
    )
    print()
    print(f"pages scanned         : {total_pages}")
    print(f"pages over 300KB cap  : {total_over} (cap {REIMAGE_MAX_BYTES:,} bytes)")
    print(f"downgraded to size6   : {total_s6}")
    print(f"downgraded to size5   : {total_s5}"
          + (f"  ({total_still} still over 300KB, kept size5 and warned)" if total_still else ""))
    print(f"kept current bytes    : {total_kept} (ladder not smaller / not replaceable)")
    untouched_books = [r for r in rows if not r["changed"]]
    print(f"books byte-untouched  : {len(untouched_books)}"
          + (" (" + ", ".join(str(r["id"]) for r in untouched_books) + ")" if untouched_books else ""))
    print(f"library before        : {mib(before_total)} MiB (book dirs; + index.json outside)")
    print(f"library after         : {mib(after_total)} MiB  (target <= 20 MiB "
          f"-> {'OK' if after_total <= 20 * 1024 * 1024 else 'OVER'})")
    print(f"final total           : {confirmations['final_total_mib']} MiB "
          f"(library/books/ incl. index.json; target <= 20 MiB "
          f"-> {'OK' if confirmations['final_total_ok'] else 'OVER'})")
    print()
    print("page <=300KB changed  : "
          f"{confirmations['small_pages_changed']} of {confirmations['small_pages']} "
          f"-- {'OK (none changed)' if confirmations['small_pages_changed'] == 0 else 'FAILED'}")
    print("other files changed   : "
          f"{confirmations['other_files_changed']} "
          f"(book.json / thumb.jpg / under-cap pages must stay byte-identical -- "
          f"{'OK' if confirmations['other_files_changed'] == 0 else 'FAILED'})")

    all_warnings = [w for row in rows for w in row.get("warnings") or []] + warnings
    print()
    if all_warnings:
        print("warnings:")
        for w in all_warnings:
            print(f"  - {w}")
    else:
        print("warnings: none")

    print()
    if errors:
        print(f"VALIDATION FAILED ({len(errors)} error(s)):")
        for err in errors:
            print(f"  ! {err}")
    else:
        print("validation: OK (JPEG magic+size, page counts vs lastPagePosition, "
              "attribution CC BY + year, text-page floor)")


def cmd_reimage(args: argparse.Namespace) -> int:
    out_root = Path(args.out)
    if not out_root.is_dir():
        print(f"error: library dir not found: {out_root}", file=sys.stderr)
        return 2
    book_dirs = sorted(
        (d for d in out_root.iterdir() if d.is_dir() and (d / "book.json").exists()),
        key=lambda d: (0, int(d.name)) if d.name.isdigit() else (1, d.name),
    )
    if not book_dirs:
        print(f"error: no book dirs with book.json under {out_root}", file=sys.stderr)
        return 2

    fetcher = Fetcher(use_cache=not args.no_cache)
    print(f"== fetch_books.py reimage: {len(book_dirs)} books in {out_root} ==", file=sys.stderr)
    print(f"cap: page-*.jpg over {REIMAGE_MAX_BYTES:,} B (300KB) drop size7 -> size6 -> size5",
          file=sys.stderr)

    # before-snapshot (size + sha256) of every file: proves what stayed untouched
    before: dict[Path, tuple[int, str]] = {}
    for book_dir in book_dirs:
        for f in sorted(book_dir.iterdir()):
            if f.is_file():
                data = f.read_bytes()
                before[f] = (len(data), hashlib.sha256(data).hexdigest())

    rows: list[dict] = []
    for i, book_dir in enumerate(book_dirs, start=1):
        print(f"[{i:02d}/{len(book_dirs):02d}] book {book_dir.name} ...",
              end=" ", file=sys.stderr, flush=True)
        try:
            row = reimage_book(fetcher, book_dir)
        except Exception as err:
            row = {
                "id": book_dir.name,
                "title": f"FAILED: {err}",
                "pages": 0,
                "before_bytes": 0,
                "after_bytes": 0,
                "over": 0,
                "to_size6": 0,
                "to_size5": 0,
                "still_over": 0,
                "kept_same": 0,
                "changed": [],
                "warnings": [f"reimage failed: {err}"],
            }
            print("FAILED", file=sys.stderr)
        else:
            delta = row["before_bytes"] - row["after_bytes"]
            print(
                f"{len(row['changed'])} page(s) replaced, saved {delta:,} B"
                if row["changed"]
                else "untouched",
                file=sys.stderr,
            )
        rows.append(row)

    # confirmations over the full before/after snapshot
    small_pages = small_pages_changed = 0
    other_files_changed = 0
    for path, (size, digest) in before.items():
        after_digest = file_digest(path) if path.exists() else None
        changed = after_digest != digest
        is_page = path.name.startswith("page-") and path.suffix == ".jpg"
        if is_page and size <= REIMAGE_MAX_BYTES:
            small_pages += 1
            if changed:
                small_pages_changed += 1
        elif not is_page or size <= REIMAGE_MAX_BYTES:
            if changed:
                other_files_changed += 1
    final_total = sum(
        p.stat().st_size for d in book_dirs for p in d.iterdir() if p.is_file()
    ) + (out_root / "index.json").stat().st_size
    confirmations = {
        "small_pages": small_pages,
        "small_pages_changed": small_pages_changed,
        "other_files_changed": other_files_changed,
        "final_total_mib": f"{final_total / (1024.0 * 1024.0):.2f}",
        "final_total_ok": final_total <= 20 * 1024 * 1024,
    }

    # same validation pass as download (meta_lpp unknown here -> lpp check skipped)
    errors, warnings = validate_library(out_root, rows, {})
    for row in rows:
        if not (out_root / str(row["id"]) / "book.json").exists():
            errors.append(f"book {row['id']}: book.json missing")

    print_reimage_report(rows, errors, warnings, confirmations)
    print(f"bytes fetched      : {fetcher.stats()}")
    return 1 if errors else 0


# ---------------------------------------------------------------------------
# subcommand: manifest
# ---------------------------------------------------------------------------

MANIFEST_SOURCE = "StoryWeaver by Pratham Books"
MANIFEST_SOURCE_HOME = "www.storyweaver.org.in"
NOTICES_DEFAULT = Path(__file__).resolve().parent.parent / "THIRD-PARTY-NOTICES.md"
NOTICES_HEADING = "## StoryWeaver storybooks (library/)"
PG_NOTICES_HEADING = "## Project Gutenberg storybooks (library/)"
AUDIO_CREDITS_LINE = (
    "Page narration audio generated with Xiaomi MiMo TTS "
    "(mimo-v2.5-tts-voicedesign)."
)
AUDIO_CREDITS_LINE_CLONE = (
    "Page narration audio generated with Xiaomi MiMo TTS "
    "(base voice designed with mimo-v2.5-tts-voicedesign, narration "
    "synthesized with mimo-v2.5-tts-voiceclone)."
)
BASE_VOICE_SAMPLE = Path(__file__).resolve().parent / "voice" / "base.mp3"


def audio_credits_line() -> str:
    """The ONE narration credit line matching the current synthesis mode.

    ``tools/voice/base.mp3`` present at stamp time -> the voiceclone variant
    (base voice designed with voicedesign, narration synthesized with
    voiceclone); otherwise the plain voicedesign line. CREDITS.md is
    regenerated wholesale from this single pick, so switching modes replaces
    the other variant in place -- exactly one of the two lines is ever
    written (idempotent upsert, never stacked).
    """
    return AUDIO_CREDITS_LINE_CLONE if BASE_VOICE_SAMPLE.is_file() else AUDIO_CREDITS_LINE

# book.json fields the three artifacts need (every manifest field must exist)
BOOK_REQUIRED = (
    "id", "shelfOrder", "title", "level", "pageCount", "sourceUrl",
    "attribution", "publisher", "publishedYear", "authors", "license",
)

NOTICES_SECTION = """\
---

## StoryWeaver storybooks (library/)

- The storybooks under `library/books/` are third-party story content from
  **StoryWeaver by Pratham Books** (https://storyweaver.org.in), licensed
  under **CC BY 4.0**. Copyright Pratham Books / the credited authors,
  illustrators and rightsholders.
- The story content is used unmodified (only image resolution differs).
- Per-book attribution is in `library/CREDITS.md` and in each
  `library/books/*/book.json` (`attribution` field, also shown in the game's
  reader credits screen).
- Source: https://storyweaver.org.in
- License: https://creativecommons.org/licenses/by/4.0/
"""

PG_NOTICES_SECTION = """\
---

## Project Gutenberg storybooks (library/)

- Ten public-domain Beatrix Potter storybooks under `library/books/` are
  third-party story content from **Project Gutenberg**
  (https://www.gutenberg.org): "The Tale of Peter Rabbit" (1902), "The Tale
  of Benjamin Bunny" (1904), "The Tale of Squirrel Nutkin" (1903), "The
  Tale of Jemima Puddle-Duck" (1908), "The Tale of Tom Kitten" (1907), "The
  Tale of Mr. Jeremy Fisher" (1906), "The Tale of Mrs. Tiggy-Winkle"
  (1905), "The Tailor of Gloucester" (1903), "The Tale of the Flopsy
  Bunnies" (1909) and "The Tale of Two Bad Mice" (1904).
- Text and original illustrations by Beatrix Potter (first published
  1902-1909, Frederick Warne & Co.). Public domain in the USA.
- The story content is used unmodified (only image resolution differs).
- Per-book attribution is in `library/CREDITS.md` and in each
  `library/books/*/book.json` (`attribution` field, also shown in the game's
  reader credits screen).
- Source: https://www.gutenberg.org (per-book eBook pages in
  `library/CREDITS.md`)
"""


def load_shelf_books(books_root: Path) -> tuple[list[dict], list[str]]:
    """Every ``library/books/{id}/book.json``, sorted by ``shelfOrder`` (1..n)."""
    books: list[dict] = []
    errors: list[str] = []
    for bj_path in sorted(books_root.glob("*/book.json")):
        label = f"book {bj_path.parent.name}"
        try:
            data = json.loads(bj_path.read_text(encoding="utf-8"))
        except (OSError, ValueError) as err:
            errors.append(f"{label}: book.json unreadable: {err}")
            continue
        missing = [k for k in BOOK_REQUIRED if k not in data]
        if missing:
            errors.append(f"{label}: book.json missing field(s): {', '.join(missing)}")
            continue
        if str(data["id"]) != bj_path.parent.name:
            errors.append(f"{label}: id {data['id']} != directory name {bj_path.parent.name}")
        pages = data.get("pages") or []
        if data.get("pageCount") != len(pages):
            errors.append(f"{label}: pageCount {data.get('pageCount')} != {len(pages)} pages")
        # license-aware attribution rule: CC BY books must name CC BY; the
        # public-domain Beatrix Potter books must name "public domain".
        license_name = str(data.get("license") or "")
        attribution = str(data.get("attribution") or "")
        if license_name.startswith("CC BY"):
            if "CC BY" not in attribution:
                errors.append(f"{label}: attribution does not contain 'CC BY'")
        elif license_name == "Public Domain":
            if "public domain" not in attribution.lower():
                errors.append(f"{label}: attribution does not contain 'public domain'")
        else:
            errors.append(f"{label}: unsupported license {license_name!r}")
        if not valid_jpeg(bj_path.parent / "thumb.jpg"):
            errors.append(f"{label}: thumb.jpg missing or not a valid JPEG")
        for page in pages:
            image = str(page.get("image") or "")
            if image and not (bj_path.parent / image).is_file():
                errors.append(f"{label}: referenced {image} is missing on disk")
        data.setdefault("illustrators", [])
        books.append(data)
    try:
        books.sort(key=lambda d: int(d["shelfOrder"]))
    except (TypeError, ValueError) as err:
        errors.append(f"shelfOrder not an int somewhere: {err}")
        return books, errors
    orders = [int(d["shelfOrder"]) for d in books]
    if orders != list(range(1, len(books) + 1)):
        errors.append(f"shelfOrder not contiguous 1..{len(books)}: {orders}")
    return books, errors


def manifest_entry(book: dict) -> dict:
    """One library/manifest.json entry; every field present, paths from library/."""
    book_id = int(book["id"])
    return {
        "id": book_id,
        "shelfOrder": int(book["shelfOrder"]),
        "title": str(book["title"]),
        "level": int(book["level"]),
        "pageCount": int(book["pageCount"]),
        "authors": list(book.get("authors") or []),
        "illustrators": list(book.get("illustrators") or []),
        "thumb": f"books/{book_id}/thumb.jpg",
        "book": f"books/{book_id}/book.json",
        "sourceUrl": str(book["sourceUrl"]),
        "license": str(book["license"]),
    }


def build_manifest(books: list[dict]) -> dict:
    licenses: list[str] = []
    for book in books:  # first-seen (shelf) order: ["CC BY 4.0", "Public Domain"]
        name = str(book.get("license") or "")
        if name not in licenses:
            licenses.append(name)
    return {
        "licenses": licenses,
        "source": MANIFEST_SOURCE,
        "count": len(books),
        "books": [manifest_entry(b) for b in books],
    }


def book_has_audio(book: dict) -> bool:
    """True when any page carries a stamped ``audio`` path."""
    return any(str(p.get("audio") or "") for p in book.get("pages") or [])


def name_join(names) -> str:
    return ", ".join(str(n) for n in names) if names else "(none)"


def cc_by_line(book: dict) -> str:
    """The standard CC BY attribution pattern for one book."""
    illustrators = book.get("illustrators") or []
    ill_part = f", illustrated by {name_join(illustrators)}" if illustrators else ""
    return (
        f'"{book["title"]}" by {name_join(book.get("authors") or [])}{ill_part}. '
        f'© {book.get("publishedYear")} {book.get("publisher")}. '
        f'Source: {book["sourceUrl"]}. License: {LICENSE} ({LICENSE_URL}). '
        f"Used unmodified; only image resolution differs."
    )


def credits_entry(n: int, book: dict) -> str:
    lines = [
        f'## {n}. {book["title"]} (id {book["id"]})',
        "",
        f'- **title:** {book["title"]}',
        f'- **authors:** {name_join(book.get("authors") or [])}',
        f'- **illustrators:** {name_join(book.get("illustrators") or [])}',
        f'- **publishedYear:** {book.get("publishedYear")}',
        f'- **publisher:** {book.get("publisher")}',
        f'- **sourceUrl:** {book["sourceUrl"]}',
        f"- **license:** {LICENSE} ({LICENSE_URL})",
        "",
        textwrap.fill(
            "CC BY attribution: " + cc_by_line(book),
            width=78,
            break_long_words=False,
            break_on_hyphens=False,
        ),
        "",
        f"Verbatim `attribution` text from `library/books/{book['id']}/book.json`:",
        "",
        f'> {book["attribution"]}',
        "",
    ]
    if book_has_audio(book):
        lines[-1:-1] = ["", audio_credits_line()]
    return "\n".join(lines)


def pd_credits_section(books: list[dict]) -> str:
    """The "Public domain — Beatrix Potter (Project Gutenberg)" credits block."""
    lines = [
        "## Public domain — Beatrix Potter (Project Gutenberg)",
        "",
        textwrap.fill(
            "The following public-domain titles complete the shelf. Each was "
            "written and illustrated by Beatrix Potter (Frederick Warne & Co., "
            "first published 1902-1909) and is public domain in the USA; the "
            "text and its illustrations come from Project Gutenberg.",
            width=78,
            break_long_words=False,
            break_on_hyphens=False,
        ),
        "",
    ]
    for i, book in enumerate(books, start=1):
        pg_id = book["id"]
        lines += [
            f'{i}. **{book["title"]}** ({book.get("publishedYear")}) — '
            f"Project Gutenberg eBook #{pg_id}: "
            f"https://www.gutenberg.org/ebooks/{pg_id}",
            textwrap.fill(
                f"Text and illustrations by Beatrix Potter, public domain in "
                f"the USA, source Project Gutenberg eBook #{pg_id}.",
                width=78,
                initial_indent="   ",
                subsequent_indent="   ",
                break_long_words=False,
                break_on_hyphens=False,
            ),
        ]
        if book_has_audio(book):
            lines += ["", "   " + audio_credits_line()]
        lines += [""]
    return "\n".join(lines) + "\n"


def credits_markdown(books: list[dict]) -> str:
    cc_books = [b for b in books if str(b.get("license") or "").startswith("CC BY")]
    pd_books = [b for b in books if str(b.get("license") or "") == "Public Domain"]
    head = [
        "# Library storybook credits",
        "",
        textwrap.fill(
            f"The StoryWeaver storybooks in `library/books/` are content "
            f"licensed {LICENSE} from {MANIFEST_SOURCE} ({MANIFEST_SOURCE_HOME}). "
            f"License: {LICENSE_URL}. In short: storybooks are used unmodified; "
            f"only image resolution differs. The shelf also holds public-domain "
            f"Beatrix Potter titles from Project Gutenberg (their section is at "
            f"the end).",
            width=78,
            break_long_words=False,
            break_on_hyphens=False,
        ),
        "",
        textwrap.fill(
            "One entry per CC BY 4.0 book follows, in shelf order: the standard "
            "CC BY attribution pattern and, below it, the verbatim `attribution` "
            "text carried in that book's book.json (the verbatim block names the "
            "actual rightsholders -- some titles credit Room to Read, not "
            "Pratham Books).",
            width=78,
            break_long_words=False,
            break_on_hyphens=False,
        ),
        "",
        "",
    ]
    entries = [credits_entry(i, b) for i, b in enumerate(cc_books, start=1)]
    out = "\n".join(head) + "\n".join(entries)
    if pd_books:
        out += "\n" + pd_credits_section(pd_books)
    return out


def upsert_notices_section(notices_path: Path, heading: str, section: str) -> str:
    """Append one notices section at the end of THIRD-PARTY-NOTICES.md.

    Re-runs replace the previously appended section in place so regeneration
    never duplicates it and never touches the rest of the file (including a
    sibling section appended after it).
    Returns "appended", "replaced" or "unchanged".
    """
    body = notices_path.read_text(encoding="utf-8")
    m = re.search(rf"^{re.escape(heading)}$", body, re.MULTILINE)
    if m is None:
        notices_path.write_text(body.rstrip("\n") + "\n\n" + section, encoding="utf-8")
        return "appended"
    start = m.start()
    if start >= 5 and body[start - 5 : start] == "---\n\n":
        start -= 5  # the section's own --- separator came along on append
    nxt = re.search(r"^## ", body[m.end() :], re.MULTILINE)
    end = m.end() + nxt.start() if nxt else len(body)
    if nxt is not None and end >= 5 and body[end - 5 : end] == "---\n\n":
        end -= 5  # the NEXT section's separator belongs to that section
    if body[start:end].rstrip("\n") == section.rstrip("\n"):
        return "unchanged"
    notices_path.write_text(body[:start] + section + body[end:], encoding="utf-8")
    return "replaced"


def cmd_manifest(args: argparse.Namespace) -> int:
    books_root = Path(args.out)
    if not books_root.is_dir():
        print(f"error: library books dir not found: {books_root}", file=sys.stderr)
        return 2
    books, errors = load_shelf_books(books_root)
    if errors:
        print(f"== fetch_books.py manifest: {len(errors)} error(s), nothing written ==")
        for err in errors:
            print(f"  ! {err}")
        return 1

    library_dir = books_root.parent
    manifest_path = library_dir / "manifest.json"
    credits_path = library_dir / "CREDITS.md"
    notices_path = Path(args.notices)

    manifest = build_manifest(books)
    manifest_path.write_text(
        json.dumps(manifest, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
    )
    credits_path.write_text(credits_markdown(books), encoding="utf-8")
    notices_action = upsert_notices_section(
        notices_path, NOTICES_HEADING, NOTICES_SECTION)
    pg_notices_action = upsert_notices_section(
        notices_path, PG_NOTICES_HEADING, PG_NOTICES_SECTION)

    print("== fetch_books.py manifest -- final report ==")
    print(f"books read         : {len(books)} (from {books_root})")
    print(f"manifest           : {manifest_path} (count {manifest['count']})")
    print(f"credits            : {credits_path}")
    print(f"notices            : {notices_path} ({notices_action}, "
          f"pg {pg_notices_action})")
    print()
    for book in books:
        entry = manifest_entry(book)
        print(f'{entry["shelfOrder"]:2d}. id {entry["id"]} -- {entry["title"]} '
              f'({entry["pageCount"]} pages)')
    print()
    print("validation: OK (required fields, dir==id, pageCount==len(pages), "
          "attribution license-aware, thumb JPEG, page files present, "
          "shelfOrder 1..n)")
    return 0


# ---------------------------------------------------------------------------
# subcommand: audio
# ---------------------------------------------------------------------------

AUDIO_NAME_RE = re.compile(r"^page-(\d+)\.(mp3|wav)$")


def scan_book_audio(book_dir: Path) -> dict[int, str]:
    """Disk truth: page number -> book-relative ``audio/page-NN.{mp3,wav}``.

    Canonical zero-padded ``page-{n:02d}`` names win over other digit
    paddings; ``mp3`` wins over ``wav`` at equal names.
    """
    audio_dir = book_dir / "audio"
    found: dict[int, tuple[tuple[int, int], str]] = {}
    if not audio_dir.is_dir():
        return {}
    for path in sorted(audio_dir.iterdir()):
        match = AUDIO_NAME_RE.match(path.name)
        if not match or not path.is_file():
            continue
        n = int(match.group(1))
        prio = (
            0 if match.group(1) == f"{n:02d}" else 1,
            0 if match.group(2) == "mp3" else 1,
        )
        if n not in found or prio < found[n][0]:
            found[n] = (prio, f"audio/{path.name}")
    return {n: rel for n, (_prio, rel) in found.items()}


def cmd_audio(args: argparse.Namespace) -> int:
    """Stamp/unstamp book.json ``pages[].audio``, then run the manifest path.

    Stamping is driven by the ``audio/page-NN.{mp3,wav}`` files on disk (the
    outputs of ``tools/fetch_audio.py``): each matching page gets its relative
    ``audio`` path, stale ``audio`` fields whose files are gone are removed,
    and nothing else in book.json is touched. Manifest + CREDITS are then
    regenerated through the SAME code path ``manifest`` uses.
    """
    books_root = Path(args.out)
    if not books_root.is_dir():
        print(f"error: library books dir not found: {books_root}", file=sys.stderr)
        return 2
    stamped = removed = 0
    rows: list[str] = []
    for bj_path in sorted(books_root.glob("*/book.json")):
        book_dir = bj_path.parent
        try:
            data = json.loads(bj_path.read_text(encoding="utf-8"))
        except (OSError, ValueError) as err:
            print(f"error: book {book_dir.name}: book.json unreadable: {err}",
                  file=sys.stderr)
            return 1
        found = scan_book_audio(book_dir)
        changed = False
        book_stamped = book_removed = 0
        for page in data.get("pages") or []:
            n = int(page.get("n") or 0)
            has_field = "audio" in page
            current = page.get("audio")
            current_ok = (
                has_field and bool(current) and (book_dir / str(current)).is_file()
            )
            if current_ok:
                continue  # stamped and present: leave it untouched
            want = found.get(n)
            if want is None:
                if has_field:
                    del page["audio"]  # stale: the file is gone
                    changed = True
                    book_removed += 1
            elif not has_field or current != want:
                page["audio"] = want
                changed = True
                book_stamped += 1
        if not changed:
            continue
        bj_path.write_text(
            json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
        )
        stamped += book_stamped
        removed += book_removed
        rows.append(
            f"book {book_dir.name}: stamped {book_stamped}, removed {book_removed}"
        )

    print("== fetch_books.py audio -- stamp report ==")
    for row in rows or ["no book.json changes"]:
        print(f"  {row}")
    print(f"totals: stamped {stamped} field(s), removed {removed} field(s)")
    print()
    return cmd_manifest(args)


# ---------------------------------------------------------------------------
# entry point
# ---------------------------------------------------------------------------

def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="fetch_books.py",
        description="StoryWeaver book ingest for the lily-game library shelf.",
    )
    sub = parser.add_subparsers(dest="command", required=True)

    p_cand = sub.add_parser(
        "candidates",
        help="Build the curation shortlist (JSON + Markdown) of English storybooks.",
    )
    p_cand.add_argument(
        "--min-english",
        type=int,
        default=TARGET_ENGLISH,
        help=f"stop paging books-search at this many English books (default {TARGET_ENGLISH}; spec floor 120)",
    )
    p_cand.add_argument(
        "--meta-limit",
        type=int,
        default=META_FETCH_LIMIT,
        help=f"per-story metadata fetches for page counts, top by reads (default {META_FETCH_LIMIT})",
    )
    p_cand.add_argument(
        "--final-target",
        type=int,
        default=FINAL_TARGET,
        help=f"aim for this many finalists after the page-count filter (default {FINAL_TARGET})",
    )
    p_cand.add_argument(
        "--no-cache",
        action="store_true",
        help="ignore /tmp/kilo/fetch-books-cache and re-fetch everything",
    )
    p_cand.set_defaults(func=cmd_candidates)

    p_down = sub.add_parser(
        "download",
        help="Download a curated shelf (page images + text + attribution) into library/books/.",
    )
    p_down.add_argument(
        "--ids",
        required=True,
        help="comma-separated StoryWeaver story ids, in shelf order "
             "(e.g. 369,2,98,...)",
    )
    p_down.add_argument(
        "--out",
        default=str(LIBRARY_DEFAULT),
        help=f"output library dir (default {LIBRARY_DEFAULT})",
    )
    p_down.add_argument(
        "--no-cache",
        action="store_true",
        help="ignore /tmp/kilo/fetch-books-cache and re-fetch everything",
    )
    p_down.set_defaults(func=cmd_download)

    p_reimg = sub.add_parser(
        "reimage",
        help="Replace page-*.jpg larger than 300KB with smaller CDN variants "
             "(size7 -> size6 -> size5); under-cap files stay byte-identical.",
    )
    p_reimg.add_argument(
        "--out",
        default=str(LIBRARY_DEFAULT),
        help=f"library dir to fix in place (default {LIBRARY_DEFAULT})",
    )
    p_reimg.add_argument(
        "--no-cache",
        action="store_true",
        help="ignore /tmp/kilo/fetch-books-cache and re-fetch everything",
    )
    p_reimg.set_defaults(func=cmd_reimage)

    p_man = sub.add_parser(
        "manifest",
        help="Regenerate library/manifest.json, library/CREDITS.md and the "
             "StoryWeaver section of THIRD-PARTY-NOTICES.md from book.json files.",
    )
    p_man.add_argument(
        "--out",
        default=str(LIBRARY_DEFAULT),
        help=f"library books dir to read (default {LIBRARY_DEFAULT})",
    )
    p_man.add_argument(
        "--notices",
        default=str(NOTICES_DEFAULT),
        help=f"THIRD-PARTY-NOTICES.md to append/refresh (default {NOTICES_DEFAULT})",
    )
    p_man.set_defaults(func=cmd_manifest)

    p_aud = sub.add_parser(
        "audio",
        help="Stamp book.json pages[].audio from audio/page-NN.{mp3,wav} on "
             "disk (remove stale fields), then regenerate manifest + CREDITS "
             "via the manifest code path.",
    )
    p_aud.add_argument(
        "--out",
        default=str(LIBRARY_DEFAULT),
        help=f"library books dir to stamp (default {LIBRARY_DEFAULT})",
    )
    p_aud.add_argument(
        "--notices",
        default=str(NOTICES_DEFAULT),
        help=f"THIRD-PARTY-NOTICES.md to append/refresh (default {NOTICES_DEFAULT})",
    )
    p_aud.set_defaults(func=cmd_audio)
    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    sys.exit(main())
